window.STRINGS = {

en: {
  // html
  page_title: 'Te Aahua o te Uaua i Waikato — Waikato-Tainui',

  // shell
  ch_opener: 'Opener',
  ch_scale: '01 · Scale',
  ch_types: '02 · Types',
  ch_where: '03 · Where',
  ch_trend: '04 · Trend',
  ch_centres: '05 · Centres',
  ch_closer: 'Closer',

  // lang picker
  lang_mi: 'Te Reo',
  lang_en: 'English',

  // title card
  masthead: 'Waikato-Tainui',
  masthead_right: 'Hardship in the Waikato  ·  May 2026',
  eyebrow_story: 'A data story',
  title_main: 'Te aahua o te\nuaua i\nWaikato.',
  title_sub: 'Three years of government hardship assistance data across the Waikato region. Where the need is greatest, what kind of help is being sought, and how it\'s changing.',
  scroll_cue: 'Scroll to explore',
  chapters_count: '05 chapters',

  // act 1
  act1_eyebrow: '01 · The Scale',
  act1_lede: 'In three years, the government granted {totalAmount} in hardship assistance across the Waikato — spread over {totalGrants} individual grants.',
  act1_stat_grants: 'Total grants issued',
  act1_stat_amount: 'Total amount granted',
  act1_stat_quarters: 'Quarters of data',
  act1_stat_tlas: 'Territorial authorities',
  act1_body1: 'These figures cover five territorial authorities in the Waikato region, from January 2023 to March 2026. Each grant represents a moment where a person or whānau reached out for help — with food, with rent, with keeping the lights on.',
  act1_body2: 'This is a count of grants, not people. One person may receive multiple grants in a quarter. The true number of people in hardship is smaller — but the frequency of need is itself part of the story.',
  act1_footer: 'Source: MSD IAP Data Warehouse, request BIIM-7241. Counts randomly rounded to base 3.',

  // act 2
  act2_eyebrow: '02 · What Kind of Help',
  act2_title: 'Food keeps people coming back. Housing costs the most.',
  act2_lede: 'Food grants account for more than half of all hardship assistance in the Waikato — but emergency housing, though far fewer grants, consumes almost half the total dollar spend.',
  act2_chart_grants: 'By number of grants',
  act2_chart_amount: 'By dollar amount',
  act2_callout_title: 'The housing gap',
  act2_callout: 'Emergency housing accounts for just {grantsPct} of grants but {amountPct} of the total spend — reflecting the high cost of emergency accommodation relative to other forms of assistance.',
  act2_body1: 'Food grants are the most frequent form of hardship assistance — overwhelmingly so. At {foodGrants} grants over three years, they outnumber the next category by more than ten to one. But each food grant is relatively small.',
  act2_body2: 'Emergency housing tells the opposite story: fewer grants, but each one involves significant cost. The total spend on emergency housing — {housingAmount} — represents the single largest line item in Waikato hardship assistance.',
  act2_compare_eyebrow: 'A closer look · The housing collapse',
  act2_compare_title: 'Strip out the emergency housing surge — what remains?',
  act2_compare_lede: 'Quarterly spend by hardship type. Emergency housing peaked in mid-2023 and collapsed through 2024 — a policy-driven step change. Food has held steady throughout, and is now the largest line of new spending almost every quarter.',
  act2_annot_collapse: 'Emergency housing collapse',
  act2_annot_peak: 'Peak: {val}',
  act2_compare_callout_title: 'The new shape',
  act2_compare_callout: 'Emergency housing fell from a quarterly peak of {housingPeak} to {housingLatest} — a drop of around nine in ten dollars. Food, meanwhile, has barely moved: still around {foodLatest} per quarter. The hardship budget hasn\'t been redirected; the housing line has simply disappeared, leaving food as the persistent core of need.',
  act2_footer: 'All hardship includes SNG, ADV, and RAP grant types.',
  type_food: 'Food',
  type_housing: 'Emergency Housing',
  type_electricity: 'Electricity',
  type_petrol: 'Petrol / Travel',
  type_gas: 'Gas',

  // act 3
  act3_eyebrow: '03 · Where',
  act3_title: 'Hamilton\'s numbers are large — but context matters.',
  act3_lede: 'Hamilton City accounts for {hamiltonPct}% of all Waikato hardship grants. But much of that is because emergency housing is physically located in the city — {housingPct}% of the region\'s emergency housing spend flows through Hamilton.',
  act3_chart_total: 'Total grants by territorial authority',
  act3_callout_title: 'Why Hamilton dominates',
  act3_callout: 'Emergency housing motels and providers are concentrated in Hamilton. People from across the Waikato — and sometimes beyond — are placed into Hamilton emergency housing, inflating the city\'s share of grants and especially of dollars. Strip out emergency housing spend and Hamilton\'s share of the total drops from {withPct}% to {withoutPct}%.',
  act3_chart_percapita: 'Grants per 1,000 residents (2023 Census)',
  act3_percapita_body: 'Per capita, the picture shifts. Hamilton still leads, but smaller authorities — particularly Ōtorohanga and Waikato District — show rates that are not far behind, despite having a fraction of the population.',
  act3_chart_maori: 'Māori population share by territorial authority',
  act3_maori_body: 'Ōtorohanga has the highest proportion of Māori residents at 32.5%, followed by Waikato District at 26.9% and Hamilton at 25.4%. These are communities at the heart of Tainui\'s rohe. The hardship data does not include ethnicity, but the overlap between where Māori live and where hardship concentrates is not a coincidence.',
  act3_chart_dollar: 'Dollar share by territorial authority',
  act3_footer: 'TLA estimated from client address. Population from 2023 Census (Stats NZ). Māori ethnicity uses total response method.',
  grants_label: 'grants',
  per_1000: 'per 1,000',
  pop_label: 'pop',

  // act 4
  act4_eyebrow: '04 · Trend',
  act4_title: 'Grant numbers hold steady.\nSpending has halved.',
  act4_lede: 'The number of hardship grants per quarter has stayed remarkably stable — around 50–60 thousand. But total spending has fallen sharply, driven by the collapse in emergency housing costs.',
  act4_chart_grants: 'Grants per quarter',
  act4_chart_amount: 'Amount granted per quarter',
  act4_callout_title: 'The divergence',
  act4_callout: 'Grant volumes dropped just {grantsDrop}% from Q1 2023 to Q1 2026, but total spending fell {amountDrop}%. The main driver: emergency housing spending peaked in mid-2023 and has dropped dramatically since — likely reflecting policy changes in emergency housing provision.',
  act4_body: 'The stability of grant numbers is striking. Quarter after quarter, roughly 50,000 grants are issued across the Waikato. The need hasn\'t gone away — it\'s the type and cost of assistance that has shifted.',
  act4_footer: 'Quarterly periods ending March, June, September, December.',

  // act 5
  act5_eyebrow: '05 · Service Centres',
  act5_title: 'Small towns, heavy loads.',
  act5_lede: 'Adjusted for population, the smaller Waikato centres — Huntly, Ngāruawāhia, Paeroa — carry hardship rates far above the urban Hamilton offices. These are also the communities with the highest Māori populations.',
  act5_tab_all: 'All Types',
  act5_tab_food: 'Food',
  act5_tab_housing: 'Housing',
  act5_tab_electricity: 'Electricity',
  act5_tab_petrol: 'Petrol',
  act5_view_percapita: 'Per capita',
  act5_view_raw: 'Raw totals',
  act5_chart_percapita: 'Grants per 1,000 residents',
  act5_chart_total: 'Total grants',
  act5_callout_title: 'The pattern',
  act5_callout: 'The communities with the highest per-capita hardship rates — {topCentres} — are also among those with the highest Māori populations ({topMaori} Māori respectively). The hardship data doesn\'t record ethnicity, but the geography speaks clearly.',
  act5_body1: 'Hamilton\'s four service centres — Kirikiriroa, Five Cross Roads, Hamilton East, and Dinsdale — show moderate per-capita rates despite high raw totals, because they serve a city of {hamiltonPop} people. Compare this to Huntly (pop. {huntlyPop}, {huntlyMaori}% Māori) or Ngāruawāhia (pop. {ngaruaPop}, {ngaruaMaori}% Māori), where the per-capita burden is significantly higher.',
  act5_body2: 'For Tainui, this is the critical insight: the communities most deeply connected to the iwi — the places where whakapapa runs deepest — are also where hardship assistance is most concentrated relative to population.',
  act5_footer: 'Per-capita rates use 2023 Census usually-resident population. Town populations approximate. Hamilton centre catchments estimated proportionally.',

  // closer
  closer_eyebrow: 'Closer',
  closer_title: 'Behind every number, a whānau.',
  closer_lede: 'This data doesn\'t capture the full picture of hardship in the Waikato. It captures the moments when people asked for help — and received it. The unrecorded need is larger still.',
  closer_body1: 'For Waikato-Tainui, these numbers carry particular weight. The rohe of the iwi overlaps substantially with the MSD service areas captured here — Huntly, Ngāruawāhia, Kirikiriroa, Te Awamutu. The communities most represented in this data are Tainui communities.',
  closer_body2: 'The data shows a region where food insecurity is persistent, where emergency housing costs have shifted dramatically, and where the structural drivers of hardship remain largely unchanged even as policy settings move.',
  closer_method_title: 'Methodology & caveats',
  method_source_h: 'Data source',
  method_source: 'Ministry of Social Development, IAP Data Warehouse. Request BIIM-7241, prepared by Business Intelligence, Insights MSD Group.',
  method_confid_h: 'Confidentiality',
  method_confid: 'All cell counts have been randomly rounded to base three. Values of 1 or 2 are rounded to 3. Published counts never differ by more than two from actual values.',
  method_grants_h: 'Grants, not people',
  method_grants: 'These are counts of grants, not individual clients. One person can receive multiple grants in a single quarter. The number of people in hardship is smaller than the grant count.',
  method_geo_h: 'Geography',
  method_geo: 'Territorial Local Authority is estimated from the client\'s address recorded by MSD at the time of the grant. Service centre reflects the MSD office that processed the application.',
  method_amount_h: 'Amount granted',
  method_amount: 'Dollar figures represent the amount granted, which is not necessarily the amount spent. Includes Special Needs Grants (SNG), Advance payments of benefit (ADV), and Recoverable Assistance Payments (RAP).',
  method_coverage_h: 'Coverage',
  method_coverage: 'Data spans 13 quarters from January 2023 to March 2026, covering five Waikato territorial authorities and 13 Waikato MSD service centres plus Pukekohe (Auckland Metro).',
  closer_footer_left: 'Waikato-Tainui · May 2026',
  closer_footer_right: 'Data: Ministry of Social Development',
  made_by: 'Made by Karo',
},

mi: {
  // html
  page_title: 'Te Aahua o te Uaua i Waikato — Waikato-Tainui',

  // shell
  ch_opener: 'Tuuwheratanga',
  ch_scale: '01 · Te Rahinga',
  ch_types: '02 · Ngaa Momo',
  ch_where: '03 · Ki Hea',
  ch_trend: '04 · Te Ia',
  ch_centres: '05 · Ngaa Taawhi',
  ch_closer: 'Whakakapi',

  // lang picker
  lang_mi: 'Te Reo',
  lang_en: 'English',

  // title card
  masthead: 'Waikato-Tainui',
  masthead_right: 'Te Uaua i Waikato  ·  Mei 2026',
  eyebrow_story: 'He koorero raraunga',
  title_main: 'Te aahua o te\nuaua i\nWaikato.',
  title_sub: 'E toru ngaa tau o ngaa raraunga aawhina uaua a te Kaawanatanga puta noa i te rohe o Waikato. Ki hea te nui o te hiahia, he aha ngaa momo aawhina e rapua ana, aa, me peehea te huringa.',
  scroll_cue: 'Panuihia ki raro',
  chapters_count: '05 upoko',

  // act 1
  act1_eyebrow: '01 · Te Rahinga',
  act1_lede: 'I roto i ngaa tau e toru, i tukuna e te Kaawanatanga he {totalAmount} hei aawhina uaua puta noa i Waikato — i waehia ki ngaa tuku {totalGrants}.',
  act1_stat_grants: 'Tapeke tuku katoa',
  act1_stat_amount: 'Tapeke puutea katoa',
  act1_stat_quarters: 'Ngaa hauwhaa raraunga',
  act1_stat_tlas: 'Ngaa mana whenua aa-rohe',
  act1_body1: 'Ko eenei tatauranga e koorero ana moo ngaa mana whenua aa-rohe e rima i te rohe o Waikato, mai i Hanuere 2023 ki Maehe 2026. Ko ia tuku he waa i tono ai teetahi tangata, teetahi whaanau raanei, moo te aawhina — moo te kai, moo te reti, moo te pupuri i ngaa rama kia kaa tonu.',
  act1_body2: 'He tatau tuku teenei, ehara i te tatau tangata. Ka taea e te tangata kotahi te whiwhi tuku maha i roto i te hauwhaa kotahi. He iti ake te tokomaha o ngaa taangata kei roto i te uaua — engari ko te auautanga o te hiahia, he waahanga tonu teenaa o te koorero.',
  act1_footer: 'Puna: Te Manatuu Whakahiato Ora, Paatengi Raraunga IAP, tono BIIM-7241. Kua aahua whakaaroarotia ngaa tatau ki te toru.',

  // act 2
  act2_eyebrow: '02 · Ngaa Momo Aawhina',
  act2_title: 'Ko te kai te mea e hoki tonu mai ai te tangata. Ko te whare ohotata te utu nui rawa.',
  act2_lede: 'Ko ngaa tuku kai te nuinga o ngaa aawhina uaua katoa i Waikato — engari ko te whare ohotata, ahakoa he iti ake ngaa tuku, e pau ana te hawhe o te puutea katoa.',
  act2_chart_grants: 'Maa te maha o ngaa tuku',
  act2_chart_amount: 'Maa te puutea',
  act2_callout_title: 'Te aawhero whare',
  act2_callout: 'Ko te whare ohotata {grantsPct} noa o ngaa tuku engari {amountPct} o te puutea katoa — e whakaatu ana i te utu nui o ngaa whare ohotata ki eetahi atu momo aawhina.',
  act2_body1: 'Ko ngaa tuku kai te momo aawhina uaua e tino kitea ana — tino nui rawa atu. I te {foodGrants} tuku i ngaa tau e toru, ka neke atu i te tekau ngaa waa i nui ake ai i te momo tuarua. Engari he iti te utu o ia tuku kai.',
  act2_body2: 'Ko te whare ohotata te koorero kee — he iti ake ngaa tuku, engari he nui te utu o ia tuku. Ko te puutea katoa moo te whare ohotata — {housingAmount} — ko te raarangi nui rawa i roto i ngaa aawhina uaua o Waikato.',
  act2_compare_eyebrow: 'He titiro hoohonu · Te hingatanga whare ohotata',
  act2_compare_title: 'Tangohia te aupiki whare ohotata — he aha kei te toe?',
  act2_compare_lede: 'Ngaa puutea ia hauwhaa maa te momo uaua. I teitei rawa te whare ohotata i te waenganui o 2023, kua hinga maa roto i te 2024 — he huringa kaupapa here. Kua noho tonu te kai, aa, koianei ināianei te raarangi nui rawa o ngaa puutea hou tata o ia hauwhaa.',
  act2_annot_collapse: 'Te hingatanga whare ohotata',
  act2_annot_peak: 'Teitei: {val}',
  act2_compare_callout_title: 'Te aahua hou',
  act2_compare_callout: 'I heke te whare ohotata mai i te teitei o te {housingPeak} ia hauwhaa ki te {housingLatest} — tata ki te iwa o ia tekau taara kua ngaro. Ko te kai, kaare i tino neke: kei te {foodLatest} tonu ia hauwhaa. Kaare te puutea uaua i whakahuria, kua ngaro noa te raarangi whare ohotata, ka mahue ko te kai te take pumau o te hiahia.',
  act2_footer: 'Ko te aawhina uaua katoa ka whakauru i ngaa tuku SNG, ADV, me RAP.',
  type_food: 'Kai',
  type_housing: 'Whare Ohotata',
  type_electricity: 'Hiko',
  type_petrol: 'Penehiini / Haere',
  type_gas: 'Kaha',

  // act 3
  act3_eyebrow: '03 · Ki Hea',
  act3_title: 'He nui ngaa nama o Kirikiriroa — engari me aro ki te horopaki.',
  act3_lede: 'Ko Kirikiriroa te {hamiltonPct}% o ngaa tuku aawhina uaua katoa i Waikato. Engari ko te nuinga o teenaa naa te mea kei reira ngaa whare ohotata — {housingPct}% o te puutea whare ohotata o te rohe e rere ana maa Kirikiriroa.',
  act3_chart_total: 'Tapeke tuku maa te mana whenua aa-rohe',
  act3_callout_title: 'He aha i nui ai a Kirikiriroa',
  act3_callout: 'Kei Kirikiriroa te nuinga o ngaa mootere me ngaa kaiwhakarato whare ohotata. Ka tukuna ngaa taangata mai i te rohe katoa o Waikato ki ngaa whare ohotata o Kirikiriroa, ka nui haere te waahanga o te taone. Tangohia te puutea whare ohotata ka heke te waahanga o Kirikiriroa mai i te {withPct}% ki te {withoutPct}%.',
  act3_chart_percapita: 'Ngaa tuku ia 1,000 taangata (Tatauranga 2023)',
  act3_percapita_body: 'Maa te tatau tangata, ka rerekee te aahua. Ko Kirikiriroa tonu te mea nui, engari ko ngaa mana whenua iti ake — tae atu ki Ootorohanga me te Takiwaa o Waikato — e tata tonu ana te reeiti, ahakoa he iti rawa te taupori.',
  act3_chart_maori: 'Te waahanga taupori Maaori maa te mana whenua aa-rohe',
  act3_maori_body: 'Ko Ootorohanga te mea nui rawa o ngaa kainoho Maaori, 32.5%, ka whai ko te Takiwaa o Waikato, 26.9%, me Kirikiriroa, 25.4%. Ko eenei ngaa hapori kei te ngaakau o te roohe o Tainui. Kaare te raraunga uaua e whakaatu ana i te iwi, engari ko te tuuranga o ngaa Maaori me te uaua, ehara i te mea tuuraru noa.',
  act3_chart_dollar: 'Te waahanga puutea maa te mana whenua aa-rohe',
  act3_footer: 'Te mana whenua aa-rohe i whakatauria mai i te whakaaturanga o te kairaau. Taupori mai i te Tatauranga 2023 (Tatauranga Aotearoa).',
  grants_label: 'tuku',
  per_1000: 'ia 1,000',
  pop_label: 'taupori',

  // act 4
  act4_eyebrow: '04 · Te Ia',
  act4_title: 'E tuu tonu ana ngaa tuku.\nKua heke te puutea.',
  act4_lede: 'Ko te maha o ngaa tuku aawhina uaua ia hauwhaa kua noho tonu — tata ki te 50–60 mano. Engari kua heke nui te puutea katoa, naa te hekenga o ngaa utu whare ohotata.',
  act4_chart_grants: 'Ngaa tuku ia hauwhaa',
  act4_chart_amount: 'Te puutea ia hauwhaa',
  act4_callout_title: 'Te wehenga',
  act4_callout: 'I heke ngaa tuku {grantsDrop}% noa mai i Q1 2023 ki Q1 2026, engari i heke te puutea katoa {amountDrop}%. Te take matua: i teitei rawa te puutea whare ohotata i te waenganui o 2023, kua heke nui mai i reira — teeraa pea e whakaatu ana i ngaa huringa kaupapa here moo te whare ohotata.',
  act4_body: 'He mea whakamiharo te noho tonu o ngaa tuku. I ia hauwhaa, tata ki te 50,000 ngaa tuku e tukuna ana puta noa i Waikato. Kaare te hiahia i ngaro — ko te momo me te utu o te aawhina kua huri.',
  act4_footer: 'Ngaa waa hauwhaa e mutu ana i Maehe, Hune, Hepetema, Tihema.',

  // act 5
  act5_eyebrow: '05 · Ngaa Taawhi Ratonga',
  act5_title: 'Ngaa taone iti, ngaa pikaunga taumaha.',
  act5_lede: 'Ina whakatikatikahia maa te taupori, ko ngaa taawhi iti o Waikato — Huntly, Ngaaruawaahia, Paeroa — e pikau ana i ngaa reeiti uaua tino nui ake i ngaa tari o Kirikiriroa. Ko eenei anoo ngaa hapori Maaori nui rawa.',
  act5_tab_all: 'Katoa',
  act5_tab_food: 'Kai',
  act5_tab_housing: 'Whare',
  act5_tab_electricity: 'Hiko',
  act5_tab_petrol: 'Penehiini',
  act5_view_percapita: 'Ia tangata',
  act5_view_raw: 'Tapeke katoa',
  act5_chart_percapita: 'Ngaa tuku ia 1,000 kainoho',
  act5_chart_total: 'Tapeke tuku',
  act5_callout_title: 'Te tauira',
  act5_callout: 'Ko ngaa hapori e nui rawa ana te reeiti uaua ia tangata — {topCentres} — ko raatau anoo ngaa hapori Maaori nui rawa ({topMaori} Maaori). Kaare te raraunga uaua e tuhia ana te iwi, engari e koorero marama ana te matawhenua.',
  act5_body1: 'Ko ngaa taawhi ratonga e whaa o Kirikiriroa — Kirikiriiroa, Five Cross Roads, Hamilton East, me Dinsdale — e whakaatu ana i ngaa reeiti aahua noa ahakoa he nui ngaa tapeke, naa te mea e mahi ana raatau moo te taone o te {hamiltonPop} tangata. Whakatauritehia ki Huntly (taupori {huntlyPop}, {huntlyMaori}% Maaori) ki Ngaaruawaahia raanei (taupori {ngaruaPop}, {ngaruaMaori}% Maaori), kei reira te pikaunga ia tangata e tino nui ake ana.',
  act5_body2: 'Moo Tainui, koianei te maaramatanga nui: ko ngaa hapori e tino hono ana ki te iwi — ngaa waahi e hoohonu rawa ana te whakapapa — ko raatau anoo kei reira te aawhina uaua e tino nui ana ia tangata.',
  act5_footer: 'Ngaa reeiti ia tangata e whakamahi ana i te taupori Tatauranga 2023. He whakatata ngaa taupori taone. Ko ngaa rohe o ngaa taawhi o Kirikiriroa he whakatau tata.',

  // closer
  closer_eyebrow: 'Whakakapi',
  closer_title: 'Kei muri i ia nama, he whaanau.',
  closer_lede: 'Kaare teenei raraunga e hopu ana i te aahua katoa o te uaua i Waikato. E hopu ana i ngaa waa i tono ai te tangata moo te aawhina — aa, i whiwhi ai. Ko te hiahia kaare i tuhia he nui ake tonu.',
  closer_body1: 'Moo Waikato-Tainui, he taumaha motuhake eenei nama. Ko te roohe o te iwi e tuuruapoo ana ki ngaa rohe ratonga o Te Manatuu Whakahiato Ora e hopu ana i konei — Huntly, Ngaaruawaahia, Kirikiriiroa, Te Awamutu. Ko ngaa hapori e nui rawa ana i roto i teenei raraunga he hapori Tainui.',
  closer_body2: 'E whakaatu ana te raraunga i teetahi rohe e mau tonu ana te hiakai, kua nui te huringa o ngaa utu whare ohotata, aa, ko ngaa take matua o te uaua kaare i huri ahakoa te nekehanga o ngaa kaupapa here.',
  closer_method_title: 'Te tikanga me ngaa whakamaaherehere',
  method_source_h: 'Te puna raraunga',
  method_source: 'Te Manatuu Whakahiato Ora, Paatengi Raraunga IAP. Tono BIIM-7241, i whakaritea e te Roopu Maaramatanga Pakihi.',
  method_confid_h: 'Te matatapu',
  method_confid: 'Kua aahua whakaaroarotia ngaa tatau katoa ki te toru. Ko ngaa uara 1, 2 raanei kua whakaaroarotia ki te 3. Kaare ngaa tatau i whakaputaina e rerekee ake ana i te rua mai i ngaa uara tuuturu.',
  method_grants_h: 'He tuku, ehara he tangata',
  method_grants: 'He tatau tuku eenei, ehara he tatau tangata takitahi. Ka taea e te tangata kotahi te whiwhi tuku maha i te hauwhaa kotahi. He iti ake te maha o ngaa taangata kei roto i te uaua i te tatau tuku.',
  method_geo_h: 'Te matawhenua',
  method_geo: 'Ko te mana whenua aa-rohe i whakatauria mai i te whakaaturanga o te kairaau i te waa o te tuku. Ko te taawhi ratonga e whakaatu ana i te tari o Te Manatuu Whakahiato Ora naana i whakahaere te tono.',
  method_amount_h: 'Te puutea i tukuna',
  method_amount: 'Ko ngaa tatauranga puutea e whakaatu ana i te puutea i tukuna, ehara i te mea i pau. Ka whakauru i ngaa Tuku Hiahia Motuhake (SNG), ngaa Utu Whakamua (ADV), me ngaa Utu Whakahoki (RAP).',
  method_coverage_h: 'Te koowhiringa',
  method_coverage: 'E 13 ngaa hauwhaa mai i Hanuere 2023 ki Maehe 2026, e koowhiri ana i ngaa mana whenua aa-rohe e rima o Waikato me ngaa taawhi ratonga 13 o Waikato me Pukekohe (Taamaki Makaurau).',
  closer_footer_left: 'Waikato-Tainui · Mei 2026',
  closer_footer_right: 'Raraunga: Te Manatuu Whakahiato Ora',
  made_by: 'I hangaia e Karo',
},

};
